- index.html
> HTML title

- package.json
Sudejau musu info i package.json
please check :)
> authors info in package.json

- index.html
Basic struktura kaip ir pas destytoja, tik musu atveju "nav" yra visada hidden iki "lg" dydzio, kuomet jau pasirodo.
> Header basic structure

- index.html
Dariau liniuote prie ekrano pridejes :)
Prasau paziurekite ir ivertinkite.
> our team commit for review

- index.html
nors judanciu bloku kiekis keicia pagal dydi, bet cia ta pati paleva kaip ir pas destytoja pavyzdi - karusele, kurios dydis lieka visada 12, bet pleciantis ekranui jame esanciu kolono skaicius dideja nuo 1 iki 3.
> "Moving blocks" basic structure

- index.html
del img tago. jis eina kartu viename stulpelija su h ir p..
manau kad ta nuotrauka vistiek bus fixuoto dydzio ir ja tada bus galima iscentruoti intervale iki lg.
nes vistiek vieta yra uzimta per visa langa tame intervale..
Del tos eilutes kur su email... Na orginale ji neaktyvi, tai ir padariau paprastai paragrafe ;)
> form layout commit

- index.html
Prasau paziurekit si commint.
Realiai interpretavau kaip viena row
ir skeleto resize ziurejau i ta spalvota background, nu nes nesugalvojau kitaip kaip padaryti.
Gal kas turi kokiu minciu?
Gal gausis sutailint vidurius su css ?
Jei turit kokiu ideju please help ;)
> free trial layout

- index.html
basic struktura.
Antroje kolonoje prirasiau extra zodziu, vien del to, kad kol kas kitu budu 3 kolona nepersimeta i kaire, net ir forsinant ja. Paskui problema issispres.
nors tam tikruose dydziuose img atrodo mazesnis, bet ten iliuzija, nes jis bus padarytas kaip background img ir sucentruotas paskui. Taciau nuo lg dydzio jis patampa col-lg-4, o salia esantis tekstas turetu buti col-lg-5, bet ji padariau col-lg-6, nufloutinau i desine, nes vieno ml tarpo nuo desnes neina padaryti.
Taipogi ten kur trys kolonos su viduje ikonom h3 ir tekstu, prie ju sukuriau klases i ateiti, kad nepasimest, bet ju css nepazymejau.
> Layout whatwedo

- css/base/base.css
imeciau i root 4 font spalvas ir 2 btn spalvas su savo anti (anti kartojasi, bet padariau, kaip destytojas parode)
> font and btn basic colors

- css/base/base.css
- index.html
padariau beveik viska. vietomis dariau kaip destytojas, kitose vietose išskyriau klases kaip h3 / h4 vien del to, kad dabrant pagal destytojo metoda pilnai, butu gavesi daugiau kodo, nes pas mus daugiau skirtingi raidziu dydziu line-height ir t.t.
prie TRY FOR FREE paragrafa palikau nukritusi i kaire, ji susitvarkysim kai jau darysim 2lvl, nes ten kontineryje tures but elementas gaubiantis h2 ir p kuriuo ir sustatysim i vietas.
jei netinka css kaip uzvardines ar turit kitu minciu sakykit.
beje, teko taisyti ir pati html ne vienoj vietoj, tai turekit omeny : )
> font css first take

- css/3rd-party/faq.css
- css/pages/home.css
- index.html
- js/pages/home.js
Patikrinkit ar tinka ir ar viskas veikia. Sukuriau FAQ sekcijai css faila 3rd-party folderyje, kad nekiltu conflictu, taip pat sukurtas js failas questions sekcijoje.
Norejau FAQ skilti damust kol buvau temoje, praleidau 4val. kol kazkas padoraus gavosi. Visus pastebejimus ir mintis issakykite komentaruose 🙂
> FAQ (lvl 2)

- css/components/button.css
- index.html
Padariau stilius, kol kai kuriu button hover keistai vaiksto, nes jiems dar reikia ir visa stulpeli stumdyti..
Ir realiai teko hoveryje koreguoti padding nes backgroud turi uzeiti i border vieta.. tai paziurekit ten..
Beje pastebejau kad HERO sekcijoje button hover dalyje turi irgi balta borderi, kuris reaguoja kitaip nei kiti..
Gero ziurejimo :D
> button styles

- css/pages/home.css
- index.html
teko irgi antra commit daryti, nes irgi uzduotys dubliavosi..
> Try out leve2

- css/components/form.css
> Basic form

- css/pages/home.css
Labas rytas,
Vakar padariau klaida ir net nepastebejau, kol font'u neatsisiunciau..
Buvau uzdejes margin-left ant visu projektu <p> tagu.
dabar istaisiau.
sorry
> clean code

- css/pages/home.css
- index.html
Sukeliau forma ir free trial sekcija..
Padariau ja su procentais, kad kai didini atitinkamai mazetu, bet kai visai maza palieka, persoka i kita stulpeli. Pavyzdyje yra su flex padaryta, as jo dar nemoku, bet sake kad dar mokisimes, tai perdarysim kai bus aisku, kaip jis veikia. 
Pridedu foto apie ka eina kkalba..
> Form free trial

- css/base/backgroundColors.css
- css/base/footer.css
- css/pages/home.css
- index.html
footerio commit.
Gan neblogai sekesi ispildyti.
Prasau paziureti ;)
> Footer for level2

- css/base/moving-blocks.css
- css/pages/home.css
- index.html
- js/components/moving-blocks.js
- js/data/blocks-section-data.js
- js/pages/home.js
Padariau block'us. 
sustailinau, patvarkiau struktura ir respons dizaina
Padariau su js kad turini renderintu..
> Moving blocks

- css/base/header.css
- css/components/circle.css
- index.html
- js/pages/home.js
padariau header su dropdownais ir pora mini js motyvu skrolinant (atsiranda po hero ir kol skrolinasi, ans buna permatomas)
ziurekit jei tinka tai suvaziuojam.. sekantis bus sandwichas, su kuriuo kova perkeliu i kita uzduoti xD
> Header lvl3

- css/base/free-trial.css
- css/components/button.css
- css/pages/home.css
- index.html
sutvarkiau forma, kad kai resizinam islaikytu tarpa su button ir app versijoje, button nugultu zemiau formos
> Free trial 4

- js/pages/home.js
sutvarkiau header, kad refresinus jis nepradingsta
> header bug fix

- css/base/faq.css
> Arrows direction change

- js/components/moving-blocks.js
- js/pages/home.js
Padariau validacija.. 
kolkas tik ta neoptimizuota
optimizacija ar bent grazesne israiska nukeliu velesniam laikui, jei liks laiko nuo projekto kitu daliu ;)
> Validation 1level

- css/components/scroll-bar.css
- css/pages/home.css
Padariau truputi ilgesni, nes kazkaip graziau ziurisi :D
> scroll bar style

- css/base/whatWeDo.css
- css/pages/home.css
- index.html
- js/pages/home.js
Animacija.. 
Apatinis scroll panailinamas atskiroje uzduotyje.
> What we do 4

- css/base/header.css
- index.html
- js/pages/home.js
padariau pagal ekrano dydzius su hamburgeriu ir perstaciau nav'o linkus pridejes akordiona.
Jei spalvos netinka - sakykit, pakeisiu, bet tiesiog nenorejau pagal originala daryt oranzines spalvos, nes jin sucksxD
> Header lvl4

- css/base/up-to-top.css
- index.html
- js/pages/home.js
sutvarkiau kaip destytojas rekomendavo..
Bet ji visvien akimirkai pasirodo.. matyt kol js sudirba..
> Up top bug
